export const soccerLeagueData = {
    england: ['English Premier League', 'EFL Championship', 'EFL League One', 'EFL League Two', 'EFL League Three'],
    spain: ['La Liga', 'Segunda División'],
    italy: ['Serie A', 'Serie B'],
    germany: ['Bundesliga', '2. Bundesliga'],
    france: ['Ligue 1', 'Ligue 2'],
    portugal: ['Primeira Liga'],
    netherlands: ['Eredivisie'],
    belgium: ['Belgian First Division A'],
    argentina: ['Argentinian Primera División'],
    brazil: ['Campeonato Brasileiro Série A'],
    usa: ['Major League Soccer (MLS)'],
    mexico: ['Liga MX'],
    japan: ['J1 League'],
    turkey: ['Süper Lig'],
    russia: ['Russian Premier League'],
    china: ['Chinese Super League'],
    australia: ['A-League'],
}